# Generated by Django 4.2.4 on 2023-08-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Nombre')),
                ('shortened', models.CharField(blank=True, max_length=40, null=True, verbose_name='Acortado')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='MM/DD/AAAA', null=True, verbose_name='Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='MM/DD/AAAA', null=True, verbose_name='Actualización')),
                ('deleted_at', models.DateTimeField(help_text='MM/DD/AAAA', null=True, verbose_name='Eliminacion')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departaments.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'towns',
                'indexes': [models.Index(fields=['name'], name='municipios_nombre_index'), models.Index(fields=['department'], name='mun_depto_id_idx')],
                'unique_together': {('id',)},
            },
        ),
    ]
