# Generated by Django 4.2.4 on 2023-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='town',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='town',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='town',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
