# Generated by Django 4.2.4 on 2023-08-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsidiary', '0001_initial'),
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificacion Email')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contraseña')),
                ('photo', models.CharField(default='default_user.jpg', max_length=45, verbose_name='Foto')),
                ('gender', models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Masculino', max_length=10, null=True, verbose_name='Genero')),
                ('document_type', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Registro Civil', 'Registro Civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], default='Cédula de Ciudadanía', max_length=25, verbose_name='Tipo Documento')),
                ('document', models.PositiveBigIntegerField(unique=True, verbose_name='Documento')),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Direccion')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nacimiento')),
                ('role', models.CharField(choices=[('Femenino', 'Femenino'), ('Empleado', 'Empleado'), ('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], default='Cliente', max_length=10, verbose_name='Rol')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='MM/DD/AAAA', null=True, verbose_name='Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='MM/DD/AAAA', null=True, verbose_name='Actualización')),
                ('deleted_at', models.DateTimeField(help_text='MM/DD/AAAA', null=True, verbose_name='Eliminacion')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiary.subsidiary', verbose_name='Sucursal')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town', verbose_name='Ciudad')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['name'], name='users_name_index'), models.Index(fields=['last_name'], name='users_last_name_index'), models.Index(fields=['town'], name='fk_usuarios_municipios1_idx'), models.Index(fields=['subsidiary'], name='fk_usuarios_sucursal1_idx')],
                'unique_together': {('id',)},
            },
        ),
    ]
