# Generated by Django 4.2.4 on 2023-08-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_role'),
        ('subsidiary', '0003_rename_direction_subsidiary_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_subsidiaries', to='user_profile.userprofile', verbose_name='Administrador'),
        ),
    ]
