# Generated by Django 4.2.4 on 2023-08-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Nombre')),
                ('region', models.CharField(choices=[('Caribe', 'Caribe'), ('Centro Oriente', 'Centro Oriente'), ('Centro Sur', 'Centro Sur'), ('Eje Cafetero - Antioquia', 'Eje Cafetero - Antioquia'), ('Llano', 'Llano'), ('Pacífico', 'Pacífico')], max_length=30, verbose_name='Región')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='MM/DD/AAAA', null=True, verbose_name='Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='MM/DD/AAAA', null=True, verbose_name='Actualización')),
                ('deleted_at', models.DateTimeField(help_text='MM/DD/AAAA', null=True, verbose_name='Eliminacion')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departments',
            },
        ),
    ]
