# Generated by Django 4.2.4 on 2023-08-10 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsidiary', '0001_initial'),
        ('towns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='default_user.jpg', max_length=45, verbose_name='Foto')),
                ('gender', models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Masculino', max_length=10, null=True, verbose_name='Genero')),
                ('document_type', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Registro Civil', 'Registro Civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], default='Cédula de Ciudadanía', max_length=25, verbose_name='Tipo Documento')),
                ('document', models.PositiveBigIntegerField(unique=True, verbose_name='Documento')),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Direccion')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nacimiento')),
                ('role', models.CharField(choices=[('Femenino', 'Femenino'), ('Empleado', 'Empleado'), ('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], default='Cliente', max_length=10, verbose_name='Rol')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='MM/DD/AAAA', null=True, verbose_name='Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='MM/DD/AAAA', null=True, verbose_name='Actualización')),
                ('deleted_at', models.DateTimeField(help_text='MM/DD/AAAA', null=True, verbose_name='Eliminacion')),
                ('subsidiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiary.subsidiary', verbose_name='Sucursal')),
                ('town_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town', verbose_name='Ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
                'indexes': [models.Index(fields=['town_id'], name='fk_usuarios_municipios1_idx'), models.Index(fields=['subsidiary_id'], name='fk_usuarios_sucursal1_idx')],
                'unique_together': {('id',)},
            },
        ),
    ]
