# Generated by Django 4.2.4 on 2023-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Empleado', 'Empleado'), ('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], default='Cliente', max_length=10, verbose_name='Rol'),
        ),
    ]
