# Generated by Django 4.2.4 on 2023-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Nombre')),
                ('region', models.CharField(choices=[('Caribe', 'Caribe'), ('Centro Oriente', 'Centro Oriente'), ('Centro Sur', 'Centro Sur'), ('Eje Cafetero - Antioquia', 'Eje Cafetero - Antioquia'), ('Llano', 'Llano'), ('Pacífico', 'Pacífico')], max_length=30, verbose_name='Región')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departments',
            },
        ),
    ]
